Ktor
navikt/helse-spanner pull request #10
Opened 2022-06-16 10:42 UTC by MikAoJk

2022-06-16 14:46 UTC, havstein commented on backend/src/main/kotlin/no/nav/spanner/Personer.kt
> +     val url = URLBuilder(baseUrl).path("api", "person-json").toString()
Vil ikke `toString` bare gi objektreferansen?

2022-06-17 05:58 UTC, MikAoJk commented
Dette funker fint:
    `
    @Test
    fun `respond with redirect on no session deprecated`() {
        withTestApplication({
            spanner(spleis, azureADConfig, true)
        }) {
            handleRequest(HttpMethod.Get, "/api/person/") {
                this.addHeader(IdType.FNR.header, "12345678910")
            }.apply {
                assertEquals(HttpStatusCode.Found, response.status())
            }
        }
    }
   `
   Denne funker ikkje
   `
    // This does not work why!!!
    @Test
    fun `respond with redirect on no session`() {
        testApplication {
            application { spanner(spleis, azureADConfig, true) }

            val response = client.get("/api/person/") {
                header(IdType.FNR.header, "12345678910")
            }
            assertEquals(HttpStatusCode.Found, response.status)
        }
    }
`

2022-06-21 06:59 UTC, jksolbakken commented
Det er noe krøll med det "sette port"-opplegget ditt, "Can not resolve request to http://localhost:65050. Main app runs at localhost:80, localhost:443"

2022-06-23 08:12 UTC, havstein commented
Det er to servere inne i bildet, appen sin (ktor `testApplication`) og en sånn `MockOAuth2Server`. Jeg fikk litt inntrykk av at det ikke er 100 % kontroll på hvem av dem som svarer på requestene, men jeg fikk ikke sett ferdig på det.

2022-08-04 06:09 UTC, jksolbakken requested changes
Jeg har fått varsel om denne hver dag i månedsvis nå, lukke eller fjerne meg som reviewer?

2022-08-04 06:12 UTC, closed without merging